//go:build darwin

package cmd

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"text/template"
	"time"
)

// launchdLabel identifies the weclaw LaunchAgent.
const launchdLabel = "com.weclaw.bridge"

// launchctl runs launchctl with args. Replaced in tests.
var launchctl = func(args ...string) ([]byte, error) {
	return exec.Command("launchctl", args...).CombinedOutput()
}

func launchdDomain() string { return "gui/" + strconv.Itoa(os.Getuid()) }

func launchdTarget() string { return launchdDomain() + "/" + launchdLabel }

func plistPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, "Library", "LaunchAgents", launchdLabel+".plist")
}

// serviceInstalled reports whether weclaw is set up as a LaunchAgent. When it is,
// launchd owns the process: start/stop/restart must go through launchctl, never
// through the self-daemonizing path, or two bridges end up running.
func serviceInstalled() bool {
	_, err := os.Stat(plistPath())
	return err == nil
}

func serviceLoaded() bool {
	_, err := launchctl("print", launchdTarget())
	return err == nil
}

func serviceStart() error {
	if serviceLoaded() {
		if out, err := launchctl("kickstart", launchdTarget()); err != nil {
			return fmt.Errorf("launchctl kickstart: %v: %s", err, bytes.TrimSpace(out))
		}
		return nil
	}
	if out, err := launchctl("bootstrap", launchdDomain(), plistPath()); err != nil {
		return fmt.Errorf("launchctl bootstrap: %v: %s", err, bytes.TrimSpace(out))
	}
	return nil
}

// serviceStop unloads the job so launchd does not respawn it. It loads again at
// next login (RunAtLoad) or on `weclaw start`.
func serviceStop() error {
	if !serviceLoaded() {
		return nil
	}
	if out, err := launchctl("bootout", launchdTarget()); err != nil {
		return fmt.Errorf("launchctl bootout: %v: %s", err, bytes.TrimSpace(out))
	}
	return nil
}

func serviceRestart() error {
	if !serviceLoaded() {
		return serviceStart()
	}
	if out, err := launchctl("kickstart", "-k", launchdTarget()); err != nil {
		return fmt.Errorf("launchctl kickstart -k: %v: %s", err, bytes.TrimSpace(out))
	}
	return nil
}

var launchdPidRe = regexp.MustCompile(`(?m)^\s*pid = (\d+)`)

// servicePid returns the pid launchd reports for the job, or 0 if it is not running.
func servicePid() int {
	out, err := launchctl("print", launchdTarget())
	if err != nil {
		return 0
	}
	m := launchdPidRe.FindSubmatch(out)
	if m == nil {
		return 0
	}
	pid, _ := strconv.Atoi(string(m[1]))
	return pid
}

const plistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>{{.Label}}</string>
  <!-- Generated by 'weclaw service install'. Manage with weclaw start/stop/restart. -->
  <key>ProgramArguments</key>
  <array>
    <string>{{.Exe}}</string>
    <string>start</string>
    <string>--foreground</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>{{.Path}}</string>
    <key>HOME</key>
    <string>{{.Home}}</string>
  </dict>
  <key>WorkingDirectory</key>
  <string>{{.WorkDir}}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>StandardOutPath</key>
  <string>{{.Log}}</string>
  <key>StandardErrorPath</key>
  <string>{{.Log}}</string>
</dict>
</plist>
`

type plistParams struct {
	Label, Exe, Path, Home, WorkDir, Log string
}

func renderPlist(p plistParams) (string, error) {
	for _, v := range []*string{&p.Label, &p.Exe, &p.Path, &p.Home, &p.WorkDir, &p.Log} {
		*v = xmlEscape(*v)
	}
	var buf bytes.Buffer
	if err := template.Must(template.New("plist").Parse(plistTemplate)).Execute(&buf, p); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func xmlEscape(s string) string {
	var buf bytes.Buffer
	_ = xml.EscapeText(&buf, []byte(s))
	return buf.String()
}

// serviceInstall writes the LaunchAgent for the running binary and loads it.
// PATH is captured from the installing shell so agents launched by the bridge
// (node-based ACP adapters, claude, codex) resolve the same way they do there.
func serviceInstall() error {
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve executable: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("resolve home: %w", err)
	}
	if err := os.MkdirAll(weclawDir(), 0o700); err != nil {
		return fmt.Errorf("create weclaw dir: %w", err)
	}
	content, err := renderPlist(plistParams{
		Label:   launchdLabel,
		Exe:     exe,
		Path:    os.Getenv("PATH"),
		Home:    home,
		WorkDir: weclawDir(),
		Log:     logFile(),
	})
	if err != nil {
		return err
	}

	// Replace whatever runs now: a previous version of the job, or an
	// unmanaged background bridge that would hold the instance lock.
	if err := serviceStop(); err != nil {
		return err
	}
	stopAllWeclaw()

	if err := os.MkdirAll(filepath.Dir(plistPath()), 0o755); err != nil {
		return fmt.Errorf("create LaunchAgents dir: %w", err)
	}
	if err := os.WriteFile(plistPath(), []byte(content), 0o644); err != nil {
		return fmt.Errorf("write plist: %w", err)
	}
	return serviceStart()
}

func serviceUninstall() error {
	if err := serviceStop(); err != nil {
		return err
	}
	if err := os.Remove(plistPath()); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove plist: %w", err)
	}
	return nil
}

// waitServicePid polls briefly for launchd to report a running pid.
func waitServicePid(timeout time.Duration) int {
	deadline := time.Now().Add(timeout)
	for {
		if pid := servicePid(); pid > 0 || time.Now().After(deadline) {
			return pid
		}
		time.Sleep(300 * time.Millisecond)
	}
}
